# Generated by Django 2.2 on 2024-11-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Темы', 'verbose_name_plural': 'Темы'},
        ),
    ]
